### ISSUE TITLE
What's the license for this data?

### ISSUE THREAD

**Issue by ptrgags** [NASA-AMMOS/3DTilesSampleData#1]
Hi there, what's the license for this dataset? I don't see any `LICENSE.md` or information in the README about this.

For some context, I'm a Cesium developer working on 3D Tiles. Today we came across the [Explore with Perseverance](https://mars.nasa.gov/mars2020/surface-experience/?drive=0&site=7) viewer and this repo. Impressive demo, and we're excited to see both this use of 3D Tiles, and your implementations in ThreeJS and Unity!

**Comment by gkjohnson** [comment]
Hi @ptrgags! Sorry for the slow response. Much like our other science products in order to use the dataset we just expect credit given to NASA/JPL-Caltech.

And thanks for your interest! If you can please share what you put together!
